services:
  atlantis:
    build: .
    container_name: atlantis
    ports:
      - "4141:4141"
    environment:
      - ATLANTIS_PORT=4141
      - ATLANTIS_REPO_ALLOWLIST=github.com/faustosm/poc-atlantis-terraform
      - ATLANTIS_ATLANTIS_URL=https://pellucid-uncavalier-latricia.ngrok-free.dev
      - ATLANTIS_GH_USER=faustosm
      - ATLANTIS_GH_TOKEN=${PERSONAL_GITHUB_TOKEN}
      - ATLANTIS_GH_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    volumes:
      - ./atlantis-data:/home/atlantis/.atlantis
      - ./repos:/repos
    restart: unless-stopped
