services:
  atlantis:
    build: .
    container_name: atlantis
    # Executa como root para evitar qualquer "permission denied" (git, limpeza, etc.)
    user: "root"
    ports:
      - "4141:4141"
    environment:
      - ATLANTIS_PORT=4141
      - ATLANTIS_REPO_ALLOWLIST=github.com/faustosm/poc-atlantis-terraform
      - ATLANTIS_ATLANTIS_URL=https://pellucid-uncavalier-latricia.ngrok-free.dev
      - ATLANTIS_GH_USER=faustosm
      - ATLANTIS_GH_TOKEN=${PERSONAL_GITHUB_TOKEN}
      - ATLANTIS_GH_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    volumes:
      # dados do Atlantis (db bolt, repos clonados, etc.)
      - ./atlantis-data:/home/atlantis/.atlantis
      # cache/repos local opcional (não é obrigatório, mas mantive como você usava)
      - ./repos:/repos
    restart: unless-stopped
