name: validate-secrets
on:
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  smoke:
    name: AWS e Infracost validate tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Verifiy AWS Credentials
        run: aws sts get-caller-identity

      - name: Setup Infracost
        uses: infracost/actions/setup@v4
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Infracost version
        run: infracost version